Nie działa dalej
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.wsbwaw.szescsloikow/com.wsbwaw.szescsloikow.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2876)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:184)
	at com.wsbwaw.szescsloikow.MainActivity.<init>(MainActivity.java:27)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1216)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
	... 11 more